server:
  port: 8989
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      develoment: true
spring:
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      force: true
mybatis:
  type-aliases-package: com.entity
  mapper-locations: classpath:/com/mapper/*.xml

